# Generated by Django 5.1.7 on 2025-05-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_user_avatar_url_user_bio_user_interests_community_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subrabble",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="rabble.subrabble",
            ),
        ),
    ]
